version: 1.0.{build}
image: Visual Studio 2022

install:
  - cmd: echo ===== INSTALL PHASE =====
  - cmd: echo Current directory is %CD%
  - cmd: dir appveyor.yml

build_script:
  - cmd: echo ===== BUILD PHASE =====
  - cmd: ver
